# Generated by Django 4.0.6 on 2022-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(error_messages={'blank': "The name field can't be blank.", 'invalid': 'The name field is invalid.', 'max_length': 'The name field must be at most 255 characters.', 'null': "The name field can't be null."}, max_length=255, verbose_name='Name'),
        ),
    ]
