# Generated by Django 4.0.6 on 2022-07-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='product',
            field=models.ForeignKey(default=1, error_messages={'blank': "The product_id field can't be blank.", 'invalid': 'The product_id field is invalid.', 'null': "The product_id field can't be null."}, on_delete=django.db.models.deletion.PROTECT, to='bills.product'),
            preserve_default=False,
        ),
    ]
