# Generated by Django 4.0.6 on 2022-07-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(error_messages={'blank': "The user_id field can't be blank.", 'invalid': 'The user_id field is invalid.', 'null': "The user_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='municipality',
            field=models.ForeignKey(error_messages={'blank': "The municipality_id field can't be blank.", 'invalid': 'The municipality_id field is invalid.', 'null': "The municipality_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.municipality'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parish',
            field=models.ForeignKey(error_messages={'blank': "The parish_id field can't be blank.", 'invalid': 'The parish_id field is invalid.', 'null': "The parish_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.parish'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(error_messages={'blank': "The state_id field can't be blank.", 'invalid': 'The state_id field is invalid.', 'null': "The state_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.state'),
        ),
    ]
