# Generated by Django 4.0.6 on 2022-07-19 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('companies', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='municipality',
            field=models.ForeignKey(error_messages={'blank': "The municipality_id field can't be blank.", 'invalid': 'The municipality_id field is invalid.', 'null': "The municipality_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.municipality'),
        ),
        migrations.AlterField(
            model_name='client',
            name='parish',
            field=models.ForeignKey(error_messages={'blank': "The parish_id field can't be blank.", 'invalid': 'The parish_id field is invalid.', 'null': "The parish_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.parish'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(error_messages={'blank': "The user_id field can't be blank.", 'invalid': 'The user_id field is invalid.', 'null': "The user_id field can't be null."}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
